spring:
  application:
    name: api-transactions
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

springdoc:
  api-docs:
    path: /swagger-ui/api-docs
  swagger-ui:
    path: /index.html
